name: janmr blog
markdown: kramdown
highlighter: rouge
encoding: utf-8
url: http://blog.janmr.com
excerpt_separator: <span></span>
permalink: /:year/:month/:title.html
baseurl: /
author: Jan Marthedal Rasmussen
title: janmr blog
rss_name: blogfeed.xml
exclude: [mathstats.py,vendor]
disqus: true
sass:
    style: :compressed
